install.packages("sf", dependencies = TRUE)
install.packages("e1071")
install.packages("ggmap")
install.packages("spatstat")
install.packages("tidyverse")
install.packages("spdep")
install.packages("epitools")
install.packages("spatialkernel")
install.packages("sp")
install.packages("gdal")
install.packages("spdep")
install.packages("raster")
install.packages("rasterVis")
install.packages("plotly")
install.packages("leaflet")